-- Programmers (JOIN) 5월 식품들의 총매출 조회하기
SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * SUM(FO.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT FP
INNER JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID ASC