-- Programmers (SELECT) 서울에 위치한 식당 목록 출력하기
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A
LEFT JOIN (SELECT REST_ID, REVIEW_SCORE
          FROM REST_REVIEW) AS B
    ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY REST_ID
HAVING SCORE IS NOT NULL
ORDER BY SCORE DESC, A.FAVORITES DESC