-- Programmers (GROUP BY) 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY REGEXP '과자|국|김치|식용유'
    GROUP BY CATEGORY
) B ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.MAX_PRICE
ORDER BY A.PRICE DESC