-- Programmers (GROUP BY) 언어별 개발자 분류하기
SELECT (CASE
            WHEN COUNT(CASE WHEN S.CATEGORY = 'Front End' THEN 1 END) > 0 AND
				COUNT(CASE WHEN S.NAME = 'Python' THEN 1 END) > 0 THEN 'A'
            WHEN COUNT(CASE WHEN S.NAME = 'C#' THEN 1 END) > 0 THEN 'B'
            WHEN COUNT(CASE WHEN S.CATEGORY = 'Front End' THEN 1 END) > 0 THEN 'C'
        END) AS GRADE,
        D.ID, D.EMAIL
FROM SKILLCODES AS S
LEFT OUTER JOIN DEVELOPERS AS D ON S.CODE & D.SKILL_CODE
GROUP BY D.ID, D.EMAIL
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID;