-- Programmers (GROUP BY) 입양 시각 구하기(2)
WITH RECURSIVE EMPTY_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM EMPTY_TABLE WHERE HOUR < 23
)

SELECT A.HOUR, COUNT(B.ANIMAL_ID) AS COUNT
FROM EMPTY_TABLE AS A
LEFT JOIN (SELECT ANIMAL_ID, HOUR(DATETIME) AS HOUR
          FROM ANIMAL_OUTS) AS B 
	ON A.HOUR = B.HOUR
GROUP BY A.HOUR
ORDER BY HOUR