-- Programmers (String, Date) 자동차 대여 기록 별 대여 금액 구하기
SELECT HC.HISTORY_ID, ROUND(HC.DAILY_FEE * (1 - IFNULL(P.DISCOUNT_RATE, 0) / 100) * HC.DAYS) AS FEE
FROM (SELECT H.HISTORY_ID, C.DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS,
      CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'    
      END AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_CAR AS C
      LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON H.CAR_ID = C.CAR_ID
      WHERE C.CAR_TYPE = '트럭'
     ) AS HC
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON HC.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HC.HISTORY_ID DESC