-- Programmers (GROUP BY) 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM AUTHOR AS A, BOOK AS B, BOOK_SALES AS BS
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01' AND
	B.BOOK_ID = BS.BOOK_ID AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC