-- Programmers (String, Date) 취소되지 않은 진료 예약 조회하기
SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D, APPOINTMENT A
WHERE A.MCDP_CD = 'CS'
    AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
    AND APNT_CNCL_YN = 'N'
    AND A.PT_NO = P.PT_NO
    AND A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD