-- Programmers (SUM, MAX, MIN) 물고기 종류 별 대어 찾기
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A, FISH_NAME_INFO AS B
WHERE A.FISH_TYPE = B.FISH_TYPE AND
    (A.FISH_TYPE, A.LENGTH) IN
    (SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE)
ORDER BY A.ID;