-- Programmers (GROUP BY) 특정 조건을 만족하는 물고기별 수와 최대 길이 구하기
SELECT F.FISH_COUNT, F.MAX_LENGTH, F.FISH_TYPE
FROM (SELECT FISH_TYPE,
		MAX(CASE WHEN LENGTH > 10 THEN LENGTH ELSE 10 END) AS MAX_LENGTH,
        COUNT(ID) AS FISH_COUNT
      FROM FISH_INFO
      GROUP BY FISH_TYPE
      HAVING AVG(CASE WHEN LENGTH > 10 THEN LENGTH ELSE 10 END) >= 33) AS F
ORDER BY F.FISH_TYPE;