-- Programmers (JOIN) 상품을 구매한 회원 비율 구하기
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT B.USER_ID) / B.TOTAL, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS A
INNER JOIN (SELECT USER_ID, COUNT(USER_ID) OVER() AS TOTAL
            FROM USER_INFO
            WHERE YEAR(JOINED) = 2021) AS B
    ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH